services:
  mongodb:
    image: mongo:latest
    container_name: url_shortener_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./back-end
    container_name: url_shortener_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
    - DATABASE_CONNECTION_STRING=mongodb://mongodb:27017/urlshortener
    - PORT=3000

  frontend:
    build: ./front-end
    container_name: url_shortener_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000

volumes:
  mongo_data:
