version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: url_shortener_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./fe
    container_name: url_shortener_frontend
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=http://localhost:3000

volumes:
  mongo_data:
